AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'out/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

LineLength:
  Enabled: false

BlockComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20
